# data
timestep_end: 300
timestep_len: 1

# model and training
dynamic_subgraph: True
h_dim: 128
z_dim: 4
n_gnn_blocks: 15
lr: 1.e-4
noise: null

n_total_steps: 600000
n_train_steps: 600000
lr_decay_start: 200000
lr_decay_len: 400000
lr_decay_extent: 0.01
save_interval: 100000
print_interval: 2000

selector: NCornerHybridRandomSelector
n_samples: 512
reverser: TINReverser